Add PodDistruptionBudgets when replica greater than 1
goharbor/harbor-helm pull request #1509
Opened 2023-05-17 08:00 UTC by rgarcia89

Currently there is no pdb deployed for components were the replica is defined greater than 1. This can lead to an outage of the components during a cluster update. The added pdb definitions will be added automatically once the replica size is greater than 1 and ensure that at least one replica is ready before the pod will be drained.

2023-05-23 08:38 UTC, rgarcia89 commented
@Vad1mo ready for review

2023-05-23 16:40 UTC, Vad1mo commented
I like it. It would be beneficial to make it optional:

- [ ]  add enable/disable flag, on each component an  
- [ ] Allow to set
Min amount

2023-05-24 07:41 UTC, rgarcia89 commented
Is setting the min amount really necessary? Currently at least one pod is necessary in order for the component to fulfill its tasks. Therefore I think we should be good with the fix value.

2023-05-24 15:44 UTC, Vad1mo approved these changes

2023-06-02 13:07 UTC, PeopleOfPlay commented
Thanks for the implementation, it's really cool! 

I quite agree with @Vad1mo and I understand your point of view, but harcoding values is never very good, some users may have use cases that push them to change this number. (If, for example, the harbor has a lot of simultaneous users, perhaps two replicas of a certain service is the bare minimum required to maintain the desired quality of service when operating on Kubernetes nodes.) 

In issue #1181 robinkb proposed a rather elegant solution from the [oauth2-proxy chart](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/poddisruptionbudget.yaml).

I think it would be better to set the default value to 1 and leave it up to the user to choose what best suits their needs. (ref [helm doc](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function))

It might also be cool to have the same logic with maxUnavailable fields. (ref #1182)

2023-07-12 01:28 UTC, MarcHenriot commented
@rgarcia89 I have pushed a version of the above changes in my fork, can we merge my version to yours ?

2023-07-12 14:06 UTC, rgarcia89 commented
> I forgot to sign my commits …. What do we do ?

Yeah I just signed them one by one. Should be fine now

2023-07-21 12:44 UTC, rgarcia89 commented
@Vad1mo I think this PR is ready to be merged

2023-08-02 21:47 UTC, MarcHenriot commented
There is typo in all pdb, I will push a fix to your fork.

It misses `matchLabels` in the `selector` section.

2023-09-05 11:51 UTC, rgarcia89 commented
@Vad1mo any idea when this can be merged?

2023-12-13 10:50 UTC, OrlinVasilev commented
@zyyw  can you please review that PR thank you!

2024-02-06 08:42 UTC, rgarcia89 commented
@MinerYang @Kajot-dev maybe you can have a look here too

2024-02-06 08:52 UTC, slushysnowman commented
Would be great to get this in - at the moment we're manually adding it for our Harbor setup

2024-02-06 10:47 UTC, Kajot-dev commented
That would be great to have! We're adding these besides the helm chart currently

2024-07-31 07:53 UTC, balonik commented
@zyyw please review and approve this MR. It is pending just single approval.

2024-10-10 11:02 UTC, OrlinVasilev commented
@Vad1mo I think that's good to go

2024-10-10 11:03 UTC, OrlinVasilev approved these changes

2024-11-20 23:26 UTC, phantasm66 commented
It looks like the only failing workflow integration test is due to an outdated workflow action (`deprecated version of `actions/upload-artifact: v2``). Can that be addressed and this feature be merged? 🙏

2024-12-05 13:59 UTC, rgarcia89 commented
All cleared and ready to be merged

2025-01-06 07:10 UTC, amar-opsverse approved these changes

2025-02-10 17:04 UTC, quercus-carsten commented
Hello, would it be possible to have this beneficial improvement reviewed? I'm not certain, but it appears that @zyyw may not have been active recently. Could someone else possibly assist?

2025-02-10 19:00 UTC, Kajot-dev commented
All the requirements are met. Can somebody proceed with the merge before we hit 2.13.0?

2025-08-15 13:56 UTC, OrlinVasilev approved these changes
LGTM, it's about time to merge this one!

2025-11-05 16:17 UTC, quercus-carsten commented
Would be really great to get this in - can someone merge please?

2025-11-05 17:28 UTC, OrlinVasilev commented
@reasonerjt @MinerYang any reason not to merge this one and to put it in the backlog and follow up without any information provided by you? Please respond!

2025-11-05 18:25 UTC, rgarcia89 commented
I am really wondering to see how many people it needs to get something merged. Especially given the fact that there are already 3 approvals :sweat_smile:

2025-11-12 05:49 UTC, bupd approved these changes
lgtm

2025-11-12 09:10 UTC, quercus-carsten commented
User @zyyw was requested to review, but it appears that the user has been inactive since September 2024.
There have been no contributions since then.

Is there anyone in the Harbor project who can help out?

2025-11-20 09:11 UTC, MinerYang requested changes
Hi @rgarcia89 ,
By setting PDB  minAvailable: 1 for each of the pod will have these impacts:
-  **Would create a direct conflict with resource management practices**. For example Kubernetes cannot voluntarily move or evict any of the pods from their current nodes. 
- And a PDB violation can also slow down the rolling upgrade process if new nodes aren't available to place replacement pods on, leading to increased deployment times
- PDBs are only effective for pod running with more than one replica. **A PDB for a single-replica application with minAvailable: 1 will block all voluntary disruptions, preventing node maintenance.**
  
PDB sacrifices cluster flexibility, efficiency, and maintainability. I personally do not see it as a necessarily configuration for pod and as an overhead operation for most of the Harbor deploy scenario.

So please clarify your using scenario and necessity justification  and better to make it optional.

Best,
Miner

2025-11-20 09:35 UTC, balonik commented
@MinerYang 

> Would create a direct conflict with resource management practices. For example Kubernetes cannot voluntarily move or evict any of the pods from their current nodes.

That is not true.
Eviction, because of higher `priorityClass` is not blocked as documented in https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#poddisruptionbudget-is-supported-but-not-guaranteed
Eviction, because of Node-pressue Eviction also does not respect PDB as documented here https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction

Could you please clarify which other eviction reason do you have in mind?

> And a PDB violation can also slow down the rolling upgrade process if new nodes aren't available to place replacement pods on, leading to increased deployment times

That is true, on the other hand I would rather have longer deployment times than unavailability of service. And it is the choice of the user which one he prefers.

> PDBs are only effective for pod running with more than one replica. A PDB for a single-replica application with minAvailable: 1 will block all voluntary disruptions, preventing node maintenance.

It is only applied if number of replicas is greater than 1, please check the changes in PR
And it's already optional, because default value is `false` for each pod's `podDisruptionBudget.enabled`.

Reason to have PDBs in place is to ensure HA, because in case of upgrade or graceful node termination I need to ensure the services are available during Pods restarts. Having all Pods being restarted at the same time is causing service outage and significantly impacts our systems.

BR

2025-11-20 12:00 UTC, Kajot-dev commented
> Hi @rgarcia89 , By setting PDB minAvailable: 1 for each of the pod will have these impacts:
> 
> * **Would create a direct conflict with resource management practices**. For example Kubernetes cannot voluntarily move or evict any of the pods from their current nodes.
> * And a PDB violation can also slow down the rolling upgrade process if new nodes aren't available to place replacement pods on, leading to increased deployment times
> * PDBs are only effective for pod running with more than one replica. **A PDB for a single-replica application with minAvailable: 1 will block all voluntary disruptions, preventing node maintenance.**
> 
> PDB sacrifices cluster flexibility, efficiency, and maintainability. I personally do not see it as a necessarily configuration for pod and as an overhead operation for most of the Harbor deploy scenario.
> 
> So please clarify your using scenario and necessity justification and better to make it optional.
> 
> Best, Miner

I must disagree.

The whole point of PDB is to prevent k8s from evicting all your pods at once and causing a downtime for your service.

> For example Kubernetes cannot voluntarily move or evict any of the pods from their current nodes.

That would be the case if allowed disruptions was `0` (eg. minAvailable when replicas is 1) Of course it is possible to create bad configuration, via anti-affinity or nodeSelector, but that's like saying we should not use `nodeSelector` since you can specify an invalid one.

Perhaps pdb could be made more configurable or made opt-in, but these are an essential part of any ha deployment. I've been using `pdb` with Harbor on multiple production instances for a couple of years and these have prevented many outages during maintenance, cluster upgrade, etc.

I hope that we can find a solution that works for everyone.

2026-01-09 11:20 UTC, quercus-carsten commented
Hi all,

I’d like to revisit the discussion.

First off: thanks @MinerYang for outlining the concerns. Looking at the current PR implementation, PDBs are already opt-in and additionally guarded against the single-replica case:

- In values.yaml, **each component has podDisruptionBudget.enabled: false by default**.
    
- In the templates, a **PDB is only created when podDisruptionBudget.enabled is true and replicas > 1**
    (e.g. {{- if and .Values.core.podDisruptionBudget.enabled (gt (int .Values.core.replicas) 1) }}).

So the chart won’t create a PDB for single-replica components, even if someone mistakenly enables the flag - this avoids the “allowed disruptions = 0” drain-blocking behavior you described for minAvailable: 1.

More generally, per Kubernetes documentation, PDBs are specifically about limiting voluntary disruptions (like evictions during node drain/maintenance) to preserve availability targets; they’re not inherently “in conflict with resource management” - they’re the mechanism Kubernetes provides for this purpose:

https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
https://kubernetes.io/docs/tasks/run-application/configure-pdb/

So, given **the feature is disabled by default** and **only applies to replicated workloads**, it seems **aligned with HA use cases** and **avoids impacting typical non-HA/default installs**.

In practice, users who enable PDBs are typically running Harbor in an HA setup (replicas > 1) and can tune minAvailable / maxUnavailable as needed.
If you, @MinerYang, could take another look at the current templates/values (opt-in + replicas > 1 guard), I believe this addresses the main concerns and we can move forward with merging.

2026-01-20 09:22 UTC, MinerYang approved these changes
lgtm

2026-01-20 09:24 UTC, MinerYang commented
Hi @rgarcia89 , @quercus-carsten 

Sorry for the late reply. I was just back from a sick leave. 

I believe adding an enable flag that looks good to me. Thanks for the contribution to our community.

Best,
Miner

2026-01-20 09:24 UTC, merged

2026-03-19 10:16 UTC, ricardojdsilva87 commented
Hello,
This feature was not added to any release yet, it's only on the main branch, the `1.18.3` tag was released around 1 hour ago.
Could you please check?
I've also noticed that these [2 lines ](https://github.com/goharbor/harbor-helm/blame/main/values.yaml#L688-L689)on the `values.yaml` file, are duplicated, but were here before this change was introduced. Most likely the lines were copy pasted across the different services and the already existing values were not noticed.
Thanks!

2026-03-20 14:30 UTC, afreyermuth98 commented
agreed with @ricardojdsilva87 , do you have an ETA for the release ?

2026-03-20 14:39 UTC, flaviomoringa commented
Such a simple thing... please merge this asap...  make sure others don't have to suffer what happened with us because of not having this in place.