Add lifecycle to core dpl
goharbor/harbor-helm pull request #1739
Opened 2024-03-31 19:22 UTC by derekcha

Hello,
I'm using Harbor so well, and I'm glad I was able to raise a PR like this.

What improvements does these changes make?
A 504 or EOF error occurred when rolling while using Harbor.
It looks like the pods aren't being cleaned up properly on shutdown (possibly because there is a port after AWS LB).
So I tested randomly setting the prestop(sleep 60) lifecycle for containers in Harbor Core and no errors occurred.
So, I am uploading a PR so that lifecycle settings can be done through this chart.

I will write down the link to the issue I registered below.
https://github.com/goharbor/harbor-helm/issues/1722

2024-04-11 09:03 UTC, derekcha commented
@MinerYang @zyyw 
Can you review it?

2024-04-12 02:12 UTC, zyyw commented
Hi @derekcha , thanks for contributing to harbor-helm. Could you please help to resolve the `DCO` failure as suggested here:
* https://github.com/goharbor/harbor-helm/pull/1739/checks?check_run_id=23332568346

2024-04-12 02:12 UTC, zyyw submitted a review, later dismissed

2024-04-12 06:21 UTC, Vad1mo requested changes
for consistancy reasons, It would make sense to support lifecycle on all pods not just the core.

2024-04-18 05:48 UTC, derekcha commented
@zyyw I ran it according to the link instructions and saw the message below, so it was resolved, right?
`All commits are signed off!`

@Vad1mo 
In addition to the core, lifecycle was added to other deployments and sts.

2024-05-02 04:06 UTC, derekcha commented
@zyyw Are you still discussing this PR?

2024-06-18 07:06 UTC, kimxogus commented
I want this feature too. This PR doesn't look adding default lifecycles to existing workloads, just provide a way to configure it.
@zyyw  Is there any concerns or point to discuss about in this PR?

2024-08-20 01:36 UTC, derekcha commented
@zyyw @Vad1mo
hello
Can't this PR be merged?

2024-09-02 03:23 UTC, kimxogus commented
@Vad1mo @zyyw Can anyone review this?

2024-11-01 09:26 UTC, kimxogus commented
@Vad1mo @zyyw  This PR has been holding for 7 months for discussion. Is there any issue we need to consider adding lifecycle to pods for 7 months...??? I don't know what kind of discussion is needed for this change. It just looks simple to me.
I'm having 5xx response issues for months and I believe adding lifecycles to pods could help resolving this issue to me.
Please consider reviewing and merging this PR.

2024-11-01 16:03 UTC, Vad1mo commented
> I believe adding lifecycles

What does that mean? you are not sure that it works yet?

2024-11-04 00:12 UTC, kimxogus commented
@Vad1mo  I'm using AWS ALB and I need to make pods to serve requests before connections to be drained and new pods ALB health checks to be passed.

2025-02-03 09:05 UTC, closed without merging