add custom annotation support for harbor and notary ingresses
goharbor/harbor-helm pull request #936
Opened 2021-04-27 13:19 UTC by neocorp

Hi,
This PR includes the changes to helm chart for allowing custom annotations separately for harbor and notary ingresses as opened with the issue #915 

Following structure is the way to use it:
```
ingress:
  ...
  annotations: # common annotations for ingresses
  harbor:
    annotations: # custom annotations for harbor ingress
  notary:
    annotations: # custom annotations for notary ingress
```

Closes #915

2021-04-27 15:46 UTC, Vad1mo approved these changes

2021-04-29 08:06 UTC, ywk253100 approved these changes

2021-05-03 13:43 UTC, Vad1mo commented
The reason is to specify mainly unique set of annotations per ingress to manage these ingresses differently.

For example:
- Public access to harbor but restricted access to notary within a certain IP address range, like using nginx.ingress.kubernetes.io/whitelist-source-range: annotation

Currently, we manually patch this ingress to get it to working but having the ability to specify the annotation while installing is of course preferred.

The currently available global annotation setting applies annotations across all ingresses, however this is not always desired, so this patch adds the ability to also provide annotations on each individual ingress differently.

2021-05-19 02:37 UTC, reasonerjt approved these changes

2021-05-21 05:08 UTC, reasonerjt requested changes
You need to update the values.yaml to pass the CI.

2021-05-23 21:53 UTC, neocorp commented
@reasonerjt added if statements around the annotations in template to handle when non-existent; I've already provided and empty dict `{}` in values.yaml which should be enough. I checked the tests but didn't see any regarding testing annotations. Let me know if there's anything else missing.

2021-05-28 10:53 UTC, reasonerjt approved these changes

2021-05-28 10:53 UTC, merged

2021-05-28 10:53 UTC, reasonerjt commented
Thanks!